//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorInfoSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.PartnerSales = new HashSet<PartnerSales>();
        }
    
        public int ID { get; set; }
        public int PartnerType { get; set; }
        public string Name { get; set; }
        public string CEOFirstName { get; set; }
        public string CEOMiddleName { get; set; }
        public string CEOLastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string TIN { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual PartnerType PartnerType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerSales> PartnerSales { get; set; }
    }
}
