//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorInfoSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerSales
    {
        public int ID { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Partner { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
    
        public virtual Partner Partner1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
